export enum Gender {
  Male = 'Male',
  Female = 'Female',
  female = 'female',
  male = 'male',
}

export const countries = {
  AF: 'Afghanistan (AF)',
  AX: 'Åland Islands (AX)',
  AL: 'Albania (AL)',
  DZ: 'Algeria (DZ)',
  AS: 'American Samoa (AS)',
  AD: 'Andorra (AD)',
  AO: 'Angola (AO)',
  AI: 'Anguilla (AI)',
  AQ: 'Antarctica (AQ)',
  AG: 'Antigua and Barbuda (AG)',
  AR: 'Argentina (AR)',
  AM: 'Armenia (AM)',
  AW: 'Aruba (AW)',
  AU: 'Australia (AU)',
  AT: 'Austria (AT)',
  AZ: 'Azerbaijan (AZ)',
  BS: 'Bahamas (BS)',
  BH: 'Bahrain (BH)',
  BD: 'Bangladesh (BD)',
  BB: 'Barbados (BB)',
  BY: 'Belarus (BY)',
  BE: 'Belgium (BE)',
  BZ: 'Belize (BZ)',
  BJ: 'Benin (BJ)',
  BM: 'Bermuda (BM)',
  BT: 'Bhutan (BT)',
  BO: 'Bolivia (BO)',
  BA: 'Bosnia and Herzegovina (BA)',
  BW: 'Botswana (BW)',
  BV: 'Bouvet Island (BV)',
  BR: 'Brazil (BR)',
  IO: 'British Indian Ocean Territory (IO)',
  VG: 'British Virgin Islands (VG)',
  BN: 'Brunei (BN)',
  BG: 'Bulgaria (BG)',
  BF: 'Burkina Faso (BF)',
  BI: 'Burundi (BI)',
  KH: 'Cambodia (KH)',
  CM: 'Cameroon (CM)',
  CA: 'Canada (CA)',
  CV: 'Cape Verde (CV)',
  BQ: 'Caribbean Netherlands (BQ)',
  KY: 'Cayman Islands (KY)',
  CF: 'Central African Republic (CF)',
  TD: 'Chad (TD)',
  CL: 'Chile (CL)',
  CN: 'China (CN)',
  CX: 'Christmas Island (CX)',
  CC: 'Cocos (Keeling) Islands (CC)',
  CO: 'Colombia (CO)',
  KM: 'Comoros (KM)',
  CK: 'Cook Islands (CK)',
  CR: 'Costa Rica (CR)',
  HR: 'Croatia (HR)',
  CU: 'Cuba (CU)',
  CW: 'Curaçao (CW)',
  CY: 'Cyprus (CY)',
  CZ: 'Czechia (CZ)',
  DK: 'Denmark (DK)',
  DJ: 'Djibouti (DJ)',
  DM: 'Dominica (DM)',
  DO: 'Dominican Republic (DO)',
  CD: 'DR Congo (CD)',
  EC: 'Ecuador (EC)',
  EG: 'Egypt (EG)',
  SV: 'El Salvador (SV)',
  GQ: 'Equatorial Guinea (GQ)',
  ER: 'Eritrea (ER)',
  EE: 'Estonia (EE)',
  SZ: 'Eswatini (SZ)',
  ET: 'Ethiopia (ET)',
  FK: 'Falkland Islands (FK)',
  FO: 'Faroe Islands (FO)',
  FJ: 'Fiji (FJ)',
  FI: 'Finland (FI)',
  FR: 'France (FR)',
  GF: 'French Guiana (GF)',
  PF: 'French Polynesia (PF)',
  TF: 'French Southern and Antarctic Lands (TF)',
  GA: 'Gabon (GA)',
  GM: 'Gambia (GM)',
  GE: 'Georgia (GE)',
  DE: 'Germany (DE)',
  GH: 'Ghana (GH)',
  GI: 'Gibraltar (GI)',
  GR: 'Greece (GR)',
  GL: 'Greenland (GL)',
  GD: 'Grenada (GD)',
  GP: 'Guadeloupe (GP)',
  GU: 'Guam (GU)',
  GT: 'Guatemala (GT)',
  GG: 'Guernsey (GG)',
  GN: 'Guinea (GN)',
  GW: 'Guinea-Bissau (GW)',
  GY: 'Guyana (GY)',
  HT: 'Haiti (HT)',
  HM: 'Heard Island and McDonald Islands (HM)',
  HN: 'Honduras (HN)',
  HK: 'Hong Kong (HK)',
  HU: 'Hungary (HU)',
  IS: 'Iceland (IS)',
  IN: 'India (IN)',
  ID: 'Indonesia (ID)',
  IR: 'Iran (IR)',
  IQ: 'Iraq (IQ)',
  IE: 'Ireland (IE)',
  IM: 'Isle of Man (IM)',
  IL: 'Israel (IL)',
  IT: 'Italy (IT)',
  CI: 'Ivory Coast (CI)',
  JM: 'Jamaica (JM)',
  JP: 'Japan (JP)',
  JE: 'Jersey (JE)',
  JO: 'Jordan (JO)',
  KZ: 'Kazakhstan (KZ)',
  KE: 'Kenya (KE)',
  KI: 'Kiribati (KI)',
  XK: 'Kosovo (XK)',
  KW: 'Kuwait (KW)',
  KG: 'Kyrgyzstan (KG)',
  LA: 'Laos (LA)',
  LV: 'Latvia (LV)',
  LB: 'Lebanon (LB)',
  LS: 'Lesotho (LS)',
  LR: 'Liberia (LR)',
  LY: 'Libya (LY)',
  LI: 'Liechtenstein (LI)',
  LT: 'Lithuania (LT)',
  LU: 'Luxembourg (LU)',
  MO: 'Macau (MO)',
  MG: 'Madagascar (MG)',
  MW: 'Malawi (MW)',
  MY: 'Malaysia (MY)',
  MV: 'Maldives (MV)',
  ML: 'Mali (ML)',
  MT: 'Malta (MT)',
  MH: 'Marshall Islands (MH)',
  MQ: 'Martinique (MQ)',
  MR: 'Mauritania (MR)',
  MU: 'Mauritius (MU)',
  YT: 'Mayotte (YT)',
  MX: 'Mexico (MX)',
  FM: 'Micronesia (FM)',
  MD: 'Moldova (MD)',
  MC: 'Monaco (MC)',
  MN: 'Mongolia (MN)',
  ME: 'Montenegro (ME)',
  MS: 'Montserrat (MS)',
  MA: 'Morocco (MA)',
  MZ: 'Mozambique (MZ)',
  MM: 'Myanmar (MM)',
  NA: 'Namibia (NA)',
  NR: 'Nauru (NR)',
  NP: 'Nepal (NP)',
  NL: 'Netherlands (NL)',
  NC: 'New Caledonia (NC)',
  NZ: 'New Zealand (NZ)',
  NI: 'Nicaragua (NI)',
  NE: 'Niger (NE)',
  NG: 'Nigeria (NG)',
  NU: 'Niue (NU)',
  NF: 'Norfolk Island (NF)',
  KP: 'North Korea (KP)',
  MK: 'North Macedonia (MK)',
  MP: 'Northern Mariana Islands (MP)',
  NO: 'Norway (NO)',
  OM: 'Oman (OM)',
  PK: 'Pakistan (PK)',
  PW: 'Palau (PW)',
  PS: 'Palestine (PS)',
  PA: 'Panama (PA)',
  PG: 'Papua New Guinea (PG)',
  PY: 'Paraguay (PY)',
  PE: 'Peru (PE)',
  PH: 'Philippines (PH)',
  PN: 'Pitcairn Islands (PN)',
  PL: 'Poland (PL)',
  PT: 'Portugal (PT)',
  PR: 'Puerto Rico (PR)',
  QA: 'Qatar (QA)',
  CG: 'Republic of the Congo (CG)',
  RE: 'Réunion (RE)',
  RO: 'Romania (RO)',
  RU: 'Russia (RU)',
  RW: 'Rwanda (RW)',
  BL: 'Saint Barthélemy (BL)',
  SH: 'Saint Helena, Ascension and Tristan da Cunha (SH)',
  KN: 'Saint Kitts and Nevis (KN)',
  LC: 'Saint Lucia (LC)',
  MF: 'Saint Martin (MF)',
  PM: 'Saint Pierre and Miquelon (PM)',
  VC: 'Saint Vincent and the Grenadines (VC)',
  WS: 'Samoa (WS)',
  SM: 'San Marino (SM)',
  ST: 'São Tomé and Príncipe (ST)',
  SA: 'Saudi Arabia (SA)',
  SN: 'Senegal (SN)',
  RS: 'Serbia (RS)',
  SC: 'Seychelles (SC)',
  SL: 'Sierra Leone (SL)',
  SG: 'Singapore (SG)',
  SX: 'Sint Maarten (SX)',
  SK: 'Slovakia (SK)',
  SI: 'Slovenia (SI)',
  SB: 'Solomon Islands (SB)',
  SO: 'Somalia (SO)',
  ZA: 'South Africa (ZA)',
  GS: 'South Georgia (GS)',
  KR: 'South Korea (KR)',
  SS: 'South Sudan (SS)',
  ES: 'Spain (ES)',
  LK: 'Sri Lanka (LK)',
  SD: 'Sudan (SD)',
  SR: 'Suriname (SR)',
  SJ: 'Svalbard and Jan Mayen (SJ)',
  SE: 'Sweden (SE)',
  CH: 'Switzerland (CH)',
  SY: 'Syria (SY)',
  TW: 'Taiwan (TW)',
  TJ: 'Tajikistan (TJ)',
  TZ: 'Tanzania (TZ)',
  TH: 'Thailand (TH)',
  TL: 'Timor-Leste (TL)',
  TG: 'Togo (TG)',
  TK: 'Tokelau (TK)',
  TO: 'Tonga (TO)',
  TT: 'Trinidad and Tobago (TT)',
  TN: 'Tunisia (TN)',
  TR: 'Turkey (TR)',
  TM: 'Turkmenistan (TM)',
  TC: 'Turks and Caicos Islands (TC)',
  TV: 'Tuvalu (TV)',
  UG: 'Uganda (UG)',
  UA: 'Ukraine (UA)',
  AE: 'United Arab Emirates (AE)',
  GB: 'United Kingdom (GB)',
  US: 'United States (US)',
  UM: 'United States Minor Outlying Islands (UM)',
  VI: 'United States Virgin Islands (VI)',
  UY: 'Uruguay (UY)',
  UZ: 'Uzbekistan (UZ)',
  VU: 'Vanuatu (VU)',
  VA: 'Vatican City (VA)',
  VE: 'Venezuela (VE)',
  VN: 'Vietnam (VN)',
  WF: 'Wallis and Futuna (WF)',
  EH: 'Western Sahara (EH)',
  YE: 'Yemen (YE)',
  ZM: 'Zambia (ZM)',
  ZW: 'Zimbabwe (ZW)',
};
